### PR TITLE
backend server supports setting doorlock timeout

### PR DESCRIPTION
**Pull request by marek-sterzik**

### CODE REVIEW

**Review by frantisek-hrdy — APPROVED** [review]

**Review by ihnatova03 — APPROVED** [review]

**Review by OndrejKorbel — APPROVED** [review]

**Review by ogamrima — APPROVED** [review]
krasa

**Review by charvi-pva — COMMENTED** [review]
:)

**Review by Flopca — APPROVED** [review]

**Review by petrhana — APPROVED** [review]
snad to bude fungovat

**Review by charvi-pva — APPROVED** [review]
:)

**Review by JakubLouzek — APPROVED** [review]

**Comment by petrhana** [comment]
co dela komentar

**Review by tadeascabala — APPROVED** [review]

**Pull request merged**
